on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          script:
            cd test;
            git pull;
            cp ./* /usr/share/nginx/html/
